### ISSUE TITLE
Definir claramente los accesos de los usuarios admin y las acciones que están habilitados a realizar. 

### ISSUE THREAD

**Issue by JhymerMartinez** [Silverhill/coupon-backend#16]
- Por ejemplo solo el usuario maker puede "eliminar" su propia cuenta. Un admin debería únicamente poder deshabilitarla.

**Comment by fabricioflores** [comment]
Creo q más bien sería al revés. Los usuarios que se den de baja en el sistema tendrían que tener una bandera: `disabled: true` o algo así. Y el admin, como su nombre lo indica, el único en poder dropear de la base de datos en sí.

**Comment by fabricioflores** [comment]
modificar autorización. control de acceso
