### ISSUE TITLE
Maker: Agregar cupones a campañas

### ISSUE THREAD

**Issue by JhymerMartinez** [Silverhill/coupon-backend#19]
Como usuario maker debo poder seleccionar un plan, si no tengo uno activo, con una cantidad especifica de cupones, los mismos que deberán ser agregados a una campaña a conveniencia del maker, es decir un maker puede crear campaña 1 y tomar 50 cupones de un plan de 200, luego crear campaña 2 y tomar 50 mas, así quedarían 100 en el plan.

![image](https://user-images.githubusercontent.com/3520164/38164987-4d71dbd8-34d2-11e8-987c-137b3d150350.png)

**Comment by fabricioflores** [comment]
debemos tener una relación entre la campaña y los cupones? o más bien la campaña solo limita el número de cupones? esto si tendríamos que conversarlo y tenerlo claro.
