### ISSUE TITLE
Maker, Hunter: Iniciar y concluir campaña

### ISSUE THREAD

**Issue by JhymerMartinez** [Silverhill/coupon-backend#20]
La campaña debe habilitarse para que se le presente a los hunters una vez que se cumplan los parámetros especificados en el rango de duración. Asimismo debe deshabilitarse una vez que culmine.

![image](https://user-images.githubusercontent.com/3520164/38099969-9a16f348-3341-11e8-94a4-de984167e2a3.png)

**Comment by fabricioflores** [comment]
q vamos a hacer con los cupones q no se avancen a usar durante una campaña?
