### ISSUE TITLE
Maker: Agregar segmentación de edad a la campaña que se está creado

### ISSUE THREAD

**Issue by JhymerMartinez** [Silverhill/coupon-backend#23]
![image](https://user-images.githubusercontent.com/3520164/38100204-5b895f70-3342-11e8-9504-c4e9de45cd55.png)

**Comment by fabricioflores** [comment]
tampoco creo q debe ir en el MPV. Otra consulta. tenemos edad mínima para la app? 13 o 18? o ninguna?
