### ISSUE TITLE
Maker, Hunter: Notificaciones

### ISSUE THREAD

**Issue by JhymerMartinez** [Silverhill/coupon-backend#31]
Cupon canjeado => llega al hunter => cupon con la campaña
Un Hunter agarro tu cupon => llega al maker =>  Datos el hunter y de la campaña capturada
Desde el management => llega a todos => un mensaje personalizado

**Comment by mvinan** [comment]
- maker: un usuario agarro tu cupon
- maker: cupon canjeado
- maker: fin de campana

**Comment by JhymerMartinez** [comment]
Debemos encontrar la manera de notificar a usuarios en especifico y no a todos en general
