### ISSUE TITLE
Maker: Subir imagen a Cloudinary desde el backend

### ISSUE THREAD

**Issue by JhymerMartinez** [Silverhill/coupon-backend#38]
Como maker debo tener la posibilidad de guardar una imagen en Cloudinary la misma que sera enviada  desde el frontend (por investigar), a su vez en base de datos almacenaremos únicamente una url hacia dicha imagen.

**Comment by fabricioflores** [comment]
- Imagen de usuario
- Imagen de campaña
- Logo de la empresa

**Comment by fabricioflores** [comment]
Note: howto test:
``` 
curl localhost:7001/graphql \
  -F operations='{ "query": "mutation ($file: Upload!) { singleUpload(file: $file) { id } }", "variables": { "file": null } }' \
  -F map='{ "0": ["variables.file"] }' \
  -F 0=@a.txt
```

**Comment by fabricioflores** [comment]
En el frontend: https://github.com/jaydenseric/apollo-upload-client
