### ISSUE TITLE
Hunter: Canjear cupon

### ISSUE THREAD

**Issue by JhymerMartinez** [Silverhill/coupon-backend#44]
Por detallar...

Consideraciones adicionales:
- Una vez que el cupon ha sido canjeado, la campaña a la que pertenecía dicho cupon deberá habilitarse nuevamente al hunter para poder capturar un nuevo cupon, siempre y cuando aun este habilitada dicha campaña.

Por el momento canjear por codigo

**Comment by fabricioflores** [comment]
:WAT:
