### ISSUE TITLE
Restucturación del login de usuarios

### ISSUE THREAD

**Issue by JhymerMartinez** [Silverhill/coupon-backend#48]
Debido a que se estan presentando algunas complicaciones al momento de loguearse en la vista de maker usando datos de Hunter o de Admin, debemos pensar en una posible restructuración de esta parte. Una opción puede ser llamar a queries independientes para Hunter y para Maker

**Comment by fabricioflores** [comment]
algunas consideraciones:
- el backend está devolviendo data? si es así, tenemos q controlar eso en el backend mismo
- si el backend devuelve un mensaje de error, no hay trabajo de eso al respecto y el error debería ser manejado en frontend (ahí un interceptor).
