### ISSUE TITLE
Maker: Habilitar automáticamente la campaña cuando coincida la fecha de inicio especificada

### ISSUE THREAD

**Issue by JhymerMartinez** [Silverhill/coupon-backend#51]
Como maker debo poder mi campaña habilitada una vez que la fecha inicial que haya especificado al momento de crear la campaña, coincida con la fecha en curso.

Posible solucion: utilizar un atributo virtual para validar la fecha en que debe habilitarse la campaña

**Comment by fabricioflores** [comment]
puede ser:
- con crontab y un archivo js para correrlo con node
- quitar el status de habilitada y simplemente devolver comparando fechas con la actual
