### ISSUE TITLE
Crear query para obtener todos los hunters de la empresa

### ISSUE THREAD

**Issue by leninkp** [Silverhill/coupon-backend#85]
Se refiere a los hunters que han tomado (capturado, canjeado) al menos una campaña
campos a retornar:
hunter (nombre, email, image)
numero de cupones (capturado, canjeado)

**Comment by fabricioflores** [comment]
Query:

```

{
	myHunters{
  	id
  	name
		redeemedCoupons
  	huntedCoupons
	}
}
```
Response:
```
{
  "data": {
    "myHunters": [
      {
        "id": "5ae5faf9321021472b4c5a27",
        "name": "Hunter",
        "redeemedCoupons": 1,
        "huntedCoupons": 0
      }
    ]
  }
}
```
Notes: 
- Total coupons should be the sum of both values
- `huntedCoupons` are the coupons that not be redeemed yet.
